<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>MidiPlayer.Droid</RootNamespace>
    <AssemblyName>MidiPlayer.Droid</AssemblyName>
    <ApplicationId>com.studio.meowtoon.midiplayer</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidManifest>Properties\AndroidManifest.xml</AndroidManifest>
    <SupportedOSPlatformVersion>29</SupportedOSPlatformVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE;RUNTIME_LINUX</DefineConstants>
    <AndroidLinkMode>None</AndroidLinkMode>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <Optimize>true</Optimize>
    <DefineConstants>TRACE;RUNTIME_LINUX</DefineConstants>
    <AndroidLinkMode>SdkOnly</AndroidLinkMode>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
  </PropertyGroup>

  <ItemGroup>
    <AndroidEnvironment Include="env.conf" />
  </ItemGroup>

  <ItemGroup>
    <AndroidAsset Include="Assets\NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidAsset>
    <AndroidAsset Include="Assets\NLog.xsd">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidAsset>
  </ItemGroup>

  <ItemGroup>
    <AndroidNativeLibrary Include="libs\arm64-v8a\libc++_shared.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libcharset.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libffi.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libFLAC.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libfluidsynth-assetloader.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libfluidsynth.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libgio-2.0.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libglib-2.0.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libgmodule-2.0.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libgobject-2.0.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libgthread-2.0.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libiconv.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libintl.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\liboboe.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libogg.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libsndfile.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libvorbis.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libvorbisenc.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libvorbisfile.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\libz.so" />
    <AndroidNativeLibrary Include="libs\arm64-v8a\preloadable_libiconv.so" />

    <AndroidNativeLibrary Include="libs\armeabi-v7a\libc++_shared.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libcharset.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libffi.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libFLAC.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libfluidsynth-assetloader.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libfluidsynth.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libgio-2.0.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libglib-2.0.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libgmodule-2.0.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libgobject-2.0.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libgthread-2.0.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libiconv.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libintl.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\liboboe.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libogg.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libsndfile.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libvorbis.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libvorbisenc.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libvorbisfile.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\libz.so" />
    <AndroidNativeLibrary Include="libs\armeabi-v7a\preloadable_libiconv.so" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MidiPlayer.FluidSynth\MidiPlayer.FluidSynth.csproj" />
    <ProjectReference Include="..\MidiPlayer\MidiPlayer.csproj" />
  </ItemGroup>
</Project>